name: NAV Calculator Automation
on:
  schedule:
    - cron: '00 3 * * 1-5'   # 8:30 AM IST (UTC+5:30)
    - cron: '10 10 * * 1-5'  # 3:40 PM IST (UTC+5:30)
  workflow_dispatch:  # Allows manual runs

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Install Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-driver
          
      - name: Run NAV Calculator
        run: python main.py
        
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: nav-results
          path: nav_comparison.csv